# Generated by Django 4.2.9 on 2025-06-25 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=200, verbose_name='コード名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コード',
                'verbose_name_plural': 'コード',
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='プレフィックス名')),
                ('code_type', models.CharField(choices=[('1', '組'), ('2', '部品'), ('3', '購入品')], max_length=1, verbose_name='コードタイプ')),
                ('next_number', models.IntegerField(default=1, verbose_name='次の番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プレフィックス',
                'verbose_name_plural': 'プレフィックス',
                'db_table': 'prefix',
            },
        ),
        migrations.CreateModel(
            name='SharedStructureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='グループ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '共有構造グループ',
                'verbose_name_plural': '共有構造グループ',
                'db_table': 'shared_structure_group',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ツリー名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ツリー',
                'verbose_name_plural': 'ツリー',
                'db_table': 'tree',
            },
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ノード名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('node_type', models.CharField(default='default', max_length=50, verbose_name='ノードタイプ')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='属性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm5.code', verbose_name='関連コード')),
            ],
            options={
                'verbose_name': 'ツリーノード',
                'verbose_name_plural': 'ツリーノード',
                'db_table': 'tree_node',
            },
        ),
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='階層レベル')),
                ('sequence', models.IntegerField(default=0, verbose_name='並び順')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='パス')),
                ('sharing_type', models.CharField(choices=[('independent', '独立'), ('shared', '共有')], default='independent', max_length=20, verbose_name='共有タイプ')),
                ('group_relative_path', models.CharField(blank=True, max_length=200, verbose_name='グループ内相対パス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.treenode', verbose_name='ノード')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pdm5.treestructure', verbose_name='親構造')),
                ('shared_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm5.sharedstructuregroup', verbose_name='共有グループ')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='pdm5.tree', verbose_name='ツリー')),
            ],
            options={
                'verbose_name': 'ツリー構造',
                'verbose_name_plural': 'ツリー構造',
                'db_table': 'tree_structure',
                'unique_together': {('tree', 'parent', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='TreeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('structure_add', '構造追加'), ('structure_remove', '構造削除'), ('structure_move', '構造移動'), ('node_update', 'ノード更新'), ('share_create', '共有作成'), ('share_join', '共有参加'), ('share_leave', '共有離脱')], max_length=20, verbose_name='操作')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='変更前の値')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='変更後の値')),
                ('change_reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日時')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm5.treestructure', verbose_name='対象構造')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='pdm5.tree', verbose_name='ツリー')),
            ],
            options={
                'verbose_name': 'ツリー変更ログ',
                'verbose_name_plural': 'ツリー変更ログ',
                'db_table': 'tree_change_log',
            },
        ),
        migrations.AddField(
            model_name='sharedstructuregroup',
            name='root_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.treenode', verbose_name='ルートノード'),
        ),
        migrations.CreateModel(
            name='CodeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='カテゴリ')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='タグ')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='カスタムフィールド')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='外部ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='pdm5.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コードメタデータ',
                'verbose_name_plural': 'コードメタデータ',
                'db_table': 'code_metadata',
            },
        ),
        migrations.CreateModel(
            name='CodeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除'), ('version_create', 'バージョン作成')], max_length=20, verbose_name='操作')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='変更前の値')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='変更後の値')),
                ('change_reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日時')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='pdm5.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コード変更ログ',
                'verbose_name_plural': 'コード変更ログ',
                'db_table': 'code_change_log',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.prefix', verbose_name='プレフィックス'),
        ),
        migrations.CreateModel(
            name='TreeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='バージョン')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('active', '有効'), ('archived', 'アーカイブ')], default='draft', max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, verbose_name='変更内容')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='スナップショットデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pdm5.tree', verbose_name='ツリー')),
            ],
            options={
                'verbose_name': 'ツリーバージョン',
                'verbose_name_plural': 'ツリーバージョン',
                'db_table': 'tree_version',
                'unique_together': {('tree', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TreeCodeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='単位')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.code', verbose_name='コード')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.treestructure', verbose_name='構造')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm5.tree', verbose_name='ツリー')),
            ],
            options={
                'verbose_name': 'ツリーコード数量',
                'verbose_name_plural': 'ツリーコード数量',
                'db_table': 'tree_code_quantity',
                'unique_together': {('tree', 'structure', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='バージョン')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('active', '有効'), ('inactive', '無効'), ('archived', 'アーカイブ')], default='draft', max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, verbose_name='変更内容')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pdm5.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コードバージョン',
                'verbose_name_plural': 'コードバージョン',
                'db_table': 'code_version',
                'unique_together': {('code', 'version')},
            },
        ),
    ]
