# Generated by Django 4.2.9 on 2024-12-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='pdm3.prefix')),
            ],
        ),
    ]
