# Generated by Django 4.2.9 on 2024-12-21 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0002_prefix_codecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefix',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
