# Generated by Django 4.2.9 on 2024-12-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0003_prefix_create_at_prefix_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='code_type',
            field=models.CharField(choices=[('1', '組'), ('2', '部品'), ('3', '購入品')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
