# Generated by Django 4.2.9 on 2024-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0005_codeversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
