# Generated by Django 4.2.9 on 2025-01-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0007_treeversion_rename_parentchild_treestructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeversionhistory',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_histories', to='pdm3.node'),
        ),
    ]
