# Generated by Django 5.1.7 on 2025-03-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm3', '0010_alter_treeversion_options_remove_tree_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm3.prefix'),
        ),
        migrations.AddField(
            model_name='treestructure',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
