# Generated by Django 4.2.9 on 2024-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeheader',
            name='code_header',
            field=models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名'),
        ),
    ]
