# Generated by Django 4.2.9 on 2024-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0005_rootnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='child_id',
            field=models.IntegerField(default=0, verbose_name='子ID'),
            preserve_default=False,
        ),
    ]
