# Generated by Django 4.2.9 on 2024-11-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0006_tree_child_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='child_id',
        ),
    ]
