# Generated by Django 4.2.9 on 2024-03-01 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='カテゴリ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
    ]
