# Generated by Django 4.2.9 on 2025-07-27 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=200, verbose_name='コード名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コード',
                'verbose_name_plural': 'コード',
                'db_table': 'pdm_system_code',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='プレフィックス名')),
                ('code_type', models.CharField(choices=[('1', '組'), ('2', '部品'), ('3', '購入品')], max_length=1, verbose_name='コードタイプ')),
                ('next_number', models.IntegerField(default=1, verbose_name='次の番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プレフィックス',
                'verbose_name_plural': 'プレフィックス',
                'db_table': 'pdm_system_prefix',
            },
        ),
        migrations.CreateModel(
            name='CodeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='カテゴリ')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='タグ')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='カスタムフィールド')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='外部ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='codes.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コードメタデータ',
                'verbose_name_plural': 'コードメタデータ',
                'db_table': 'pdm_system_code_metadata',
            },
        ),
        migrations.CreateModel(
            name='CodeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除'), ('version_create', 'バージョン作成')], max_length=20, verbose_name='操作')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='変更前の値')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='変更後の値')),
                ('change_reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日時')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='codes.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コード変更ログ',
                'verbose_name_plural': 'コード変更ログ',
                'db_table': 'pdm_system_code_change_log',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.prefix', verbose_name='プレフィックス'),
        ),
        migrations.CreateModel(
            name='CodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='バージョン')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('active', '有効'), ('inactive', '無効'), ('archived', 'アーカイブ')], default='draft', max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, verbose_name='変更内容')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='codes.code', verbose_name='コード')),
            ],
            options={
                'verbose_name': 'コードバージョン',
                'verbose_name_plural': 'コードバージョン',
                'db_table': 'pdm_system_code_version',
                'unique_together': {('code', 'version')},
            },
        ),
    ]
